INSERT INTO `test`.`countryinfo` (`city_id`, `CountryName`, `CityName`, `Population`, `isCapital`) VALUES ('1', 'United Kingdom', 'Osasco', '59357', '0');
INSERT INTO `test`.`countryinfo` (`city_id`, `CountryName`, `CityName`, `Population`, `isCapital`) VALUES ('2', 'United Kingdom', 'Aiseau', '1292522', '0');
INSERT INTO `test`.`countryinfo` (`city_id`, `CountryName`, `CityName`, `Population`, `isCapital`) VALUES ('3', 'Spain', 'Ambresin', '1674791', '0');
INSERT INTO `test`.`countryinfo` (`city_id`, `CountryName`, `CityName`, `Population`, `isCapital`) VALUES ('4', 'Laos', 'Bellary', '411042', '0');
INSERT INTO `test`.`countryinfo` (`city_id`, `CountryName`, `CityName`, `Population`, `isCapital`) VALUES ('5', 'Spain', 'Calvi Risorta', '630559', '0');
INSERT INTO `test`.`countryinfo` (`city_id`, `CountryName`, `CityName`, `Population`, `isCapital`) VALUES ('6', 'Poland', 'Catemu', '683892', '0');
INSERT INTO `test`.`countryinfo` (`city_id`, `CountryName`, `CityName`, `Population`, `isCapital`) VALUES ('7', 'Tunisia', 'Fairbanks', '1418093', '0');
INSERT INTO `test`.`countryinfo` (`city_id`, `CountryName`, `CityName`, `Population`, `isCapital`) VALUES ('8', 'Germany', 'Hope', '1936699', '1');
INSERT INTO `test`.`countryinfo` (`city_id`, `CountryName`, `CityName`, `Population`, `isCapital`) VALUES ('9', 'Ghana', 'Jemeppe-sur-Meuse', '1674791', '0');
INSERT INTO `test`.`countryinfo` (`city_id`, `CountryName`, `CityName`, `Population`, `isCapital`) VALUES ('10', 'Kyrgyzstan', 'Lake Cowichan', '1729360', '1');
INSERT INTO `test`.`countryinfo` (`city_id`, `CountryName`, `CityName`, `Population`, `isCapital`) VALUES ('11', 'United Kingdom', 'Lauco', '398405', '1');
INSERT INTO `test`.`countryinfo` (`city_id`, `CountryName`, `CityName`, `Population`, `isCapital`) VALUES ('12', 'Ukraine', 'Le Grand-Quevilly', '1521606', '0');
INSERT INTO `test`.`countryinfo` (`city_id`, `CountryName`, `CityName`, `Population`, `isCapital`) VALUES ('13', 'Ukraine', 'Mariquina', '131473', '0');
INSERT INTO `test`.`countryinfo` (`city_id`, `CountryName`, `CityName`, `Population`, `isCapital`) VALUES ('14', 'Poland', 'Montauban', '411042', '0');
INSERT INTO `test`.`countryinfo` (`city_id`, `CountryName`, `CityName`, `Population`, `isCapital`) VALUES ('15', 'Poland', 'Natales', '178173', '0');
INSERT INTO `test`.`countryinfo` (`city_id`, `CountryName`, `CityName`, `Population`, `isCapital`) VALUES ('16', 'Poland', 'Oxford County', '1044303', '1');
INSERT INTO `test`.`countryinfo` (`city_id`, `CountryName`, `CityName`, `Population`, `isCapital`) VALUES ('17', 'United Kingdom', 'Pepingen', '1532307', '1');
INSERT INTO `test`.`countryinfo` (`city_id`, `CountryName`, `CityName`, `Population`, `isCapital`) VALUES ('18', 'Norway', 'Pichidegua', '1336143', '0');
INSERT INTO `test`.`countryinfo` (`city_id`, `CountryName`, `CityName`, `Population`, `isCapital`) VALUES ('19', 'Ukraine', 'Pordenone', '1710803', '0');
INSERT INTO `test`.`countryinfo` (`city_id`, `CountryName`, `CityName`, `Population`, `isCapital`) VALUES ('20', 'Spain', 'Racine', '329479', '1');
INSERT INTO `test`.`countryinfo` (`city_id`, `CountryName`, `CityName`, `Population`, `isCapital`) VALUES ('21', 'United Kingdom', 'Randazzo', '352691', '0');
INSERT INTO `test`.`countryinfo` (`city_id`, `CountryName`, `CityName`, `Population`, `isCapital`) VALUES ('22', 'French Guiana', 'Rhisnes', '440448', '0');
INSERT INTO `test`.`countryinfo` (`city_id`, `CountryName`, `CityName`, `Population`, `isCapital`) VALUES ('23', 'Algeria', 'Sainte-Marie-sur-Semois', '1359415', '0');
INSERT INTO `test`.`countryinfo` (`city_id`, `CountryName`, `CityName`, `Population`, `isCapital`) VALUES ('24', 'Macao', 'Sikar', '1729360', '1');
INSERT INTO `test`.`countryinfo` (`city_id`, `CountryName`, `CityName`, `Population`, `isCapital`) VALUES ('25', 'Spain', 'Swan', '1286047', '0');
INSERT INTO `test`.`countryinfo` (`city_id`, `CountryName`, `CityName`, `Population`, `isCapital`) VALUES ('26', 'Spain', 'Thisnes', '698716', '1');
INSERT INTO `test`.`countryinfo` (`city_id`, `CountryName`, `CityName`, `Population`, `isCapital`) VALUES ('27', 'Chad', 'Vichuquén', '484902', '1');
INSERT INTO `test`.`countryinfo` (`city_id`, `CountryName`, `CityName`, `Population`, `isCapital`) VALUES ('28', 'Slovakia', 'Warsaw', '2034654', '0');
INSERT INTO `test`.`countryinfo` (`city_id`, `CountryName`, `CityName`, `Population`, `isCapital`) VALUES ('29', 'United Kingdom', 'Westrem', '1679556', '1');
INSERT INTO `test`.`countryinfo` (`city_id`, `CountryName`, `CityName`, `Population`, `isCapital`) VALUES ('30', 'Syria', 'Yellowknife', '1671911', '0');