INSERT INTO `test`.`Rating` (`RatingId`, `ReportingContextId`, `EffectiveStartTimestamp`, `EffectiveEndTimestamp`, `RatingAgencyId`, `RatingTypeId`, `RatingValue`, `Ranking`, `ECAICreditQualityStep`, `IsInferredData`, `ReferenceDataSnapshotId`, `ProcessExecutionId`) VALUES ('1', '1', '901101', '901101', '1', '1', '(P)Ba2', '79', '29', '90', '65', '40');
INSERT INTO `test`.`Rating` (`RatingId`, `ReportingContextId`, `EffectiveStartTimestamp`, `EffectiveEndTimestamp`, `RatingAgencyId`, `RatingTypeId`, `RatingValue`, `Ranking`, `ECAICreditQualityStep`, `IsInferredData`, `ReferenceDataSnapshotId`, `ProcessExecutionId`) VALUES ('2', '2', '901101', '901101', '1', '1', 'Baa1', '39', '76', '58', '6', '25');
INSERT INTO `test`.`Rating` (`RatingId`, `ReportingContextId`, `EffectiveStartTimestamp`, `EffectiveEndTimestamp`, `RatingAgencyId`, `RatingTypeId`, `RatingValue`, `Ranking`, `ECAICreditQualityStep`, `IsInferredData`, `ReferenceDataSnapshotId`, `ProcessExecutionId`) VALUES ('3', '3', '901101', '901101', '1', '1', 'Baa2', '31', '56', '96', '83', '61');
INSERT INTO `test`.`Rating` (`RatingId`, `ReportingContextId`, `EffectiveStartTimestamp`, `EffectiveEndTimestamp`, `RatingAgencyId`, `RatingTypeId`, `RatingValue`, `Ranking`, `ECAICreditQualityStep`, `IsInferredData`, `ReferenceDataSnapshotId`, `ProcessExecutionId`) VALUES ('4', '4', '901101', '901101', '1', '1', '(P)B2', '48', '98', '53', '44', '47');
INSERT INTO `test`.`Rating` (`RatingId`, `ReportingContextId`, `EffectiveStartTimestamp`, `EffectiveEndTimestamp`, `RatingAgencyId`, `RatingTypeId`, `RatingValue`, `Ranking`, `ECAICreditQualityStep`, `IsInferredData`, `ReferenceDataSnapshotId`, `ProcessExecutionId`) VALUES ('5', '5', '901101', '901101', '1', '1', '(P)B3', '98', '64', '26', '42', '49');
INSERT INTO `test`.`Rating` (`RatingId`, `ReportingContextId`, `EffectiveStartTimestamp`, `EffectiveEndTimestamp`, `RatingAgencyId`, `RatingTypeId`, `RatingValue`, `Ranking`, `ECAICreditQualityStep`, `IsInferredData`, `ReferenceDataSnapshotId`, `ProcessExecutionId`) VALUES ('6', '6', '901101', '901101', '2', '1', 'AA-', '67', '63', '12', '8', '4');
INSERT INTO `test`.`Rating` (`RatingId`, `ReportingContextId`, `EffectiveStartTimestamp`, `EffectiveEndTimestamp`, `RatingAgencyId`, `RatingTypeId`, `RatingValue`, `Ranking`, `ECAICreditQualityStep`, `IsInferredData`, `ReferenceDataSnapshotId`, `ProcessExecutionId`) VALUES ('7', '7', '901101', '901101', '3', '2', 'B+ f', '73', '16', '90', '3', '64');
INSERT INTO `test`.`Rating` (`RatingId`, `ReportingContextId`, `EffectiveStartTimestamp`, `EffectiveEndTimestamp`, `RatingAgencyId`, `RatingTypeId`, `RatingValue`, `Ranking`, `ECAICreditQualityStep`, `IsInferredData`, `ReferenceDataSnapshotId`, `ProcessExecutionId`) VALUES ('8', '8', '901101', '901101', '3', '2', 'BB f', '65', '67', '91', '63', '80');
INSERT INTO `test`.`Rating` (`RatingId`, `ReportingContextId`, `EffectiveStartTimestamp`, `EffectiveEndTimestamp`, `RatingAgencyId`, `RatingTypeId`, `RatingValue`, `Ranking`, `ECAICreditQualityStep`, `IsInferredData`, `ReferenceDataSnapshotId`, `ProcessExecutionId`) VALUES ('9', '9', '901101', '901101', '3', '2', 'BBB- f', '26', '23', '90', '3', '19');
