CREATE TABLE `test`.`instrument` (
  `InstrumentId` INT NOT NULL,
  `ReportingContextId` INT NULL,
  `EffectiveStartTimestamp` TIMESTAMP(6) NULL,
  `EffectiveEndTimestamp` TIMESTAMP(6) NULL,
  `SourceSystemId` VARCHAR(45) NULL,
  `InstrumentCode` int NULL,
  `IssuerPartyId` INT NULL,
  `GuarantorPartyId` INT NULL,
  `IssueCurrencyId` INT NULL,
  `ContactualMaturityDate` DATE NULL,
  `InstrumentStaticDataTypeId` INT NULL,
  `InstrumentCollateraTypeId` INT NULL,
  `TreasuryInstrumentTypeId` INT NULL,
  `ExchangeId` INT NULL,
  `MarketSectorId` INT NULL,
  `IssueDate` DATE NULL,
  PRIMARY KEY (`InstrumentId`));